# -*- coding: utf-8 -*-
"""pyngrok_proj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K1-Z2zAT7seW8pcjyXy4HyM3RUXm5NwP
"""

#!pip install streamlit
#! pip install pyngrok

!pip install jedi

import streamlit as st

!ls

#!ngrok authtoken 2Kdb7yIBNwhg6ahIm4dyBrZMRsh_42urMsAVouu4Lr9CwGrLk

#from pyngrok import ngrok

#!nohup streamlit run app.py &
#url = ngrok.connect(port = '8501')
#print(url)

!streamlit run app.py & npx localtunnel --port 8501

!pgrep streamlit

publ_url
